; D-39 压测环境 OPcache 调优（大内存目标 5000 QPS）
opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=512
opcache.interned_strings_buffer=32
opcache.max_accelerated_files=80000
opcache.validate_timestamps=0
opcache.revalidate_freq=0
opcache.save_comments=1
opcache.jit=1255
opcache.jit_buffer_size=256M

realpath_cache_size=4096K
realpath_cache_ttl=600
